### ISSUE TITLE
Mapa mental conjuntos 

### ISSUE THREAD

**Issue by Juan27231** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Juan27231#2]
[mapa conjuntos Juan Pablo César Hdz Stgo 1AS.pdf](https://github.com/user-attachments/files/17122533/mapa.conjuntos.Juan.Pablo.Cesar.Hdz.Stgo.1AS.pdf)

**Comment by josealfredo79** [comment]
Calificacion 19 Bien hecho y revisado..
